//get profile info types
export const GET_PROFILE_INFO_SPINNER = 'GET_PROFILE_INFO_SPINNER';
export const GET_PROFILE_INFO_SUCCESS = 'GET_PROFILE_INFO_SUCCESS';
export const GET_PROFILE_INFO_FAILED = 'GET_PROFILE_INFO_FAILED';
//update profile info types
export const USER_CHANGE_PHOTO_SUCCESSFULLY = 'USER_CHANGE_PHOTO_SUCCESSFULLY';

//update photo types
export const UPDATE_PROFILE_SPINNER = 'UPDATE_PROFILE_SPINNER';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
// change commitment filter

export const CHANGE_COMMITMENT_FILTER = 'CHANGE_COMMITMENT_FILTER';
