//get profile info types
export const GET_PROFILE_INFO_SPINNER = 'GET_PROFILE_INFO_SPINNER';
export const GET_PROFILE_INFO_SUCCESS = 'GET_PROFILE_INFO_SUCCESS';
export const GET_PROFILE_INFO_FAILED = 'GET_PROFILE_INFO_FAILED';
//update profile info types
export const USER_CHANGE_PHOTO_SUCCESSFULLY = 'USER_CHANGE_PHOTO_SUCCESSFULLY';

//update photo types
export const UPDATE_PROFILE_SPINNER = 'UPDATE_PROFILE_SPINNER';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
// change commitment filter

export const CHANGE_COMMITMENT_SPINNER = 'CHANGE_COMMITMENT_SPINNER';
export const CHANGE_COMMITMENT_SUCCESS = 'CHANGE_COMMITMENT_SUCCESS';
export const CHANGE_COMMITMENT_FAILED = 'CHANGE_COMMITMENT_FAILED';

///
export const SELECT_ABSENSE_START_DATE = 'SELECT_ABSENSE_START_DATE';
export const SELECT_ABSENSE_END_DATE = 'SELECT_ABSENSE_END_DATE';
export const ABSENSE_REASON_CHANGE = 'ABSENSE_REASON_CHANGE';
//
export const ABSENSE_REQUEST_SPINNER = 'ABSENSE_REQUEST_SPINNER';
export const ABSENSE_REQUEST_SUCCESS = 'ABSENSE_REQUEST_SUCCESS';
export const ABSENSE_REQUEST_FAILED = 'ABSENSE_REQUEST_FAILED';
